stages:
  stage1:
    cmd: python stage_01.py
    deps:
      - stage_01.py
    outs:
      - artifacts.txt


  stage2:
    cmd: python stage_02.py
    deps:
      - artifacts.txt
      - stage_02.py

